### ISSUE TITLE
Relatório de Testes

### ISSUE THREAD

**Issue by henriquefeIix** [HilbertoFernandes/GPS#1]
- [x] **Problema em Cadastro de Usuários:**
_O formulário de cadastro de usuários aceita qualquer tipo de caractere, incluindo apenas espaços em branco. **Deve-se verificar o tipo de caractere de cada campo e se certificar que o dado digitado não é composto apenas por espaços ou se há espaços em branco nas extremidades da string.**_ [[Print da Tela]](https://user-images.githubusercontent.com/32625255/39960179-73229b22-55f4-11e8-8371-e8cac534df08.PNG) 

> - _O **e-mail** deve ser uma string no formato de e-mail._ 
> - _A **matrícula** deve ser composta apenas por caracteres numéricos._
> - _O **telefone** deve ser composto apenas por caracteres numéricos._
> - _O **nome** deve ser composto apenas por caracteres alfabéticos._

**Comment by henriquefeIix** [comment]
- [ ] **Problema em Cadastro e Edição de Livros:**
_O formulário de cadastro de livro aceita qualquer tipo de caractere, incluindo apenas espaços em branco, e o campo de quantidade de exemplares aceita números negativos. **O sistema deverá verificar o dado digitado em cada campo para se certificar que o mesmo não é composto apenas por espaços ou também se há espaços nas extremidades da string. Além disso, deverá fazer com que o campo "quantidade" aceite apenas números positivos.**_

> - _O **autor** deve ser composto apenas por caracteres alfabéticos._ 
> - _O **título** deve ser composto apenas por caracteres alfabéticos._ 
> - _A **sinopse** deve ser composta apenas por caracteres alfabéticos._ 
> - _A **quantidade** deve ser composto apenas por números positivos._

![erro2](https://user-images.githubusercontent.com/32625255/39960198-ca992542-55f4-11e8-8626-3472f553dcc2.PNG)

**Comment by henriquefeIix** [comment]
- [ ] **Problema em Exclusão de Usuário:**
_É permitida a exclusão de um usuário que está logado. **Para resolver esse problema, o sistema deveria verificar se o usuário a ser excluído também é o usuário logando.**_

![erro4](https://user-images.githubusercontent.com/32625255/39960241-960a1240-55f5-11e8-91d0-8cd33b59b1ff.PNG)

**Comment by henriquefeIix** [comment]
- [ ] **Problema em Edição de Usuário:**
_Ao tentar editar dados do usuário, o sistema exibe a página de listagem de livros._

![erro 3](https://user-images.githubusercontent.com/32625255/39960285-3d2bea44-55f6-11e8-8a01-6c8abf1a08f8.PNG)

**Comment by henriquefeIix** [comment]
- [ ] **Problema em Controle de Acesso:**
_O aluno consegue acessar páginas exclusivas do funcionário (listagem de usuários e cadastro de livros) ao digitar a URL. **Ao tentar acessar essas URLs logado como aluno, o sistema deveria redirecionar o usuário para a página inicial.**_

**Comment by henriquefeIix** [comment]
- [ ] **Problema em Solicitação de Cadastro:**
_Um aluno continua se cadastrando, quando na verdade ele deveria apenas solicitar o cadastro. **Apenas se for aprovado pelo funcionário,  acesso do aluno por meio de login será liberado.**_

**Comment by henriquefeIix** [comment]
- [ ] **Problema em Formulário de Cadastro:**
_O campo de senha continua exibindo a senha do usuário em texto plano._

**Comment by henriquefeIix** [comment]
- [ ] **Problema no Armazenamento de Senhas:**
_As senhas dos usuários estão sendo armazenadas em texto plano no banco de dados._

**Comment by HilbertoFernandes** [comment]
Questões implementadas, enviando dados para reteste.
